version: '3.4'

volumes:
  esdata01:
    driver: local

services:
  web:
    build:
      context: ./web
    ports:
      - "${PORT}:80"
    volumes:
      - ./web/conf.d:/etc/nginx/conf.d:rw,cached
    depends_on:
      - frontend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - node.name=es01
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - "9288:9200"

  zookeeper:
    image: wurstmeister/zookeeper
    #tmpfs: "/datalog"
    ports:
      - "2181:2181"
  
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports: 
      - "9099:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
      - JVM_OPTS=-Xms32M -Xmx64M
      - SERVER_SERVLET_CONTEXTPATH=/
    depends_on:
      - kafka

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_CREATE_TOPICS: "NewUrl:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock

  frontend:
    image: node-yarn
    build:
      context: ./frontend
      dockerfile: ../docker/nodejs-yarn.dockerfile
    environment:
      - REACT_APP_COORDINATOR=//coordinator.${DEFAULT_HOST}
    depends_on:
      - coordinator
    volumes:
      - ./frontend:/app:rw,cached

  coordinator:
    image: node-npm
    build:
      context: ./coordinator
      dockerfile: ../docker/nodejs-npm.dockerfile
    environment:
      - DEFAULT_HOST=${DEFAULT_HOST}
      - KAFKA_HOST=kafka:9092
    depends_on:
      - kafka
    volumes:
      - ./coordinator:/app:rw,cached
      - ./.platform/routes.yaml:/app/routes.yaml:ro

  calendar:
    build:
      context: ./calendar
      dockerfile: ../docker/php.dockerfile
    volumes:
      - ./calendar:/var/www/app:rw,cached
    depends_on:
      - elasticsearch
      - kafka

  videos:
    image: ce-python
    build:
      context: ./videos
      dockerfile: ../docker/python.dockerfile
    volumes:
      - ./videos:/app
    environment:
      - KAFKA_HOST=kafka:9092
      - ELASTICSEARCH_HOST=http://elasticsearch:9200

#these projects *reuse* the built images.
  videos_worker:
    image: ce-python
    volumes:
      - ./videos:/app
    environment:
      - KAFKA_HOST=kafka:9092
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    command: "python kafkaworker.py"

  rssreader:
    image: node-npm
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    volumes:
      - ./rssreader:/app
      - ./rssreader/db:/app/db
    depends_on:
      - elasticsearch

  tweets:
    image: node-npm
    volumes:
      - ./tweets:/app
    environment:
      - KAFKA_HOST=kafka:9092
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    depends_on:
      - kafka
      - coordinator
      - elasticsearch

  comics:
    image: node-npm
    volumes:
      - ./comics:/app
    environment:
      - KAFKA_HOST=kafka:9092
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    depends_on:
      - elasticsearch
      - kafka

  rabbithole:
    image: node-npm
    volumes:
      - ./rabbithole:/app
    depends_on:
      - elasticsearch
      - kafka
