name: rabbithole
type: nodejs:10
size: S

dependencies:
  nodejs:
    pm2: "^2.4.0"

web:
  commands:
    start: "PM2_HOME=$PLATFORM_APP_DIR/run pm2 start index.js --no-daemon"
    #in this setup you will find your application stdout and stderr in /app/run/logs
  locations:
    "/":
      passthru: true

relationships:
  kafka: "kafkastreaming:kafka"
  elasticsearch: "elasticsearch:elasticsearch"

mounts:
  "/run": "shared:files/run"

disk: 128