"https://{default}/":
    type: upstream
    upstream: "frontend:http"

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"

"https://coordinator.{default}/":
  type: upstream
  upstream: "coordinator:http"

"https://rssreader.{default}/":
  type: upstream
  upstream: "rssreader:http"

"https://calendar.{default}/":
  type: upstream
  upstream: "calendar:http"

"https://tweets.{default}/":
  type: upstream
  upstream: "tweets:http"

"https://letsdopython.{default}/":
  type: upstream
  upstream: "letsdopython:http"
