"https://{default}/":
    type: upstream
    upstream: "frontend:http"

"https://www.{default}/":
  type: redirect
  to: "https://{default}/"

"https://coordinator.{default}/":
  type: upstream
  upstream: "coordinator:http"

"https://rssreader.{default}/":
  type: upstream
  upstream: "rssreader:http"

"https://calendar.{default}/":
  type: upstream
  upstream: "calendar:http"

"https://tweets.{default}/":
  type: upstream
  upstream: "tweets:http"

"https://comics.{default}/":
  type: upstream
  upstream: "comics:http"

"https://videos.{default}/":
  type: upstream
  upstream: "videos:http"

"https://rabbithole.{default}/":
  type: upstream
  upstream: "rabbithole:http"
